#! /bin/sh

#### AUTOSTART ####

bash ~/.xprofile
sxhkd &
#synclient TapButton1=1 TapButton2=3 TapButton3=2 & #For laptop touchpad
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#/home/ajrv/.config/polybar/launch.sh --cuts


#### WORKSPACES AND BORDERS ####


bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10


#Monitor allocation and their workspaces

#scratchpad
#bspc rule -a st:scratchy sticky=on state=floating rectangle=widthxheight+Xoffset+Yoffset

#Border gaps,width, and padding
bspc config border_width         1
bspc config window_gap          15
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle     true

bspc config top_padding          50
bspc config bottom_padding       50
bspc config left_padding         30
bspc config right_padding 	 30
#Focus on pointer

bspc config normal_border_color   "#282c34"
bspc config focused_border_color  "#5c6370"
bspc config presel_feedback_color "#5c6370"


bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

bspc config swallow_first_click true
